название: Синхронизировать форк

 на:
 Расписание:
 - cron: '*/30 * * * *' # каждые 30 минут
   workflow_dispatch: # задания по нажатию кнопки on

:
 синхронизация:

 запуск: ubuntu-последние

     шаги:
 - использует: TG908/fork-sync@v1.1
         с:
 github_token: $ {{ секреты.GITHUB_TOKEN }}
           владелец: llvm
           база: мастер
           руководитель: мастер
